export { default } from "@/components/layouts/AppLayout";

export const metadata = {
  title: "workmeetcoffee | home",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};
